# Generated by Django 3.2 on 2021-05-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.employee'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.checkintype')),
                ('timeCard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.timecard')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.checkintype')),
                ('timeCard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.timecard')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.workplace')),
            ],
        ),
    ]
