# Generated by Django 3.2 on 2021-05-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='worksAtCompany',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.company'),
            preserve_default=False,
        ),
    ]
