# Generated by Django 3.2 on 2021-05-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_worksatcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('employeeManager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.employee')),
            ],
        ),
    ]
