# Generated by Django 3.2 on 2021-05-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210527_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='checkInType',
        ),
    ]
