# Generated by Django 3.2 on 2021-06-01 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210527_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeCard', to='app.employee'),
        ),
    ]
