# Generated by Django 3.2 on 2021-06-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_timecard_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timeCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkIn', to='app.timecard'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='timeCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkOut', to='app.timecard'),
        ),
    ]
