# Generated by Django 3.2 on 2021-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210602_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
