# Generated by Django 3.2 on 2021-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_checkin_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timestamp',
            field=models.DateTimeField(verbose_name='time of checkin'),
        ),
    ]
