# Generated by Django 3.2 on 2021-06-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_timecard_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='companyManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='app.company'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='employeeManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to='app.employee'),
        ),
    ]
