# Generated by Django 3.2 on 2021-06-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20210606_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='companyManager',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='employeeManager',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
