# Generated by Django 3.2 on 2021-06-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='company',
            new_name='companyManager',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='employee',
            new_name='employeeManager',
        ),
    ]
