# Generated by Django 3.2 on 2021-06-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
