# Generated by Django 3.2 on 2021-06-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210614_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='timeCard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkIn', to='app.timecard'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='timeCard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkOut', to='app.timecard'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksAtCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='app.company'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='app.company'),
        ),
    ]
